# Generated by Django 6.1 on 2026-09-11 01:54

import django.db.models.deletion
import pagos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_alter_configuracionbeneficiocategoria_limite_mensual_pyg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de crédito'), ('TARJETA_DEBITO', 'Tarjeta de débito')], max_length=20, verbose_name='Tipo')),
                ('titular', models.CharField(max_length=150, verbose_name='Titular')),
                ('ultimos_cuatro_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('fecha_vencimiento', models.CharField(max_length=5, validators=[pagos.validators.validar_formato_vencimiento], verbose_name='Vencimiento')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('DESACTIVACION', 'Desactivación'), ('ACTIVACION', 'Activación'), ('ELIMINACION', 'Eliminación')], max_length=20, verbose_name='Acción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_metodos_pago', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='pagos.metodopago', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Auditoría de método de pago',
                'verbose_name_plural': 'Auditorías de métodos de pago',
                'ordering': ['-fecha'],
            },
        ),
    ]
