# Generated by Django 6.1 on 2026-09-11 02:26

import pagos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='numero_billetera',
            field=models.CharField(blank=True, max_length=20, validators=[pagos.validators.validar_numero_billetera], verbose_name='Celular asociado'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='proveedor_billetera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Proveedor de la billetera'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='fecha_vencimiento',
            field=models.CharField(blank=True, max_length=5, validators=[pagos.validators.validar_formato_vencimiento], verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de crédito'), ('TARJETA_DEBITO', 'Tarjeta de débito'), ('BILLETERA_ELECTRONICA', 'Billetera electrónica')], max_length=25, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='ultimos_cuatro_digitos',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos'),
        ),
    ]
