# Generated by Django 6.1 on 2026-09-24 20:46

import destinos.validators
import django.db.models.deletion
import pagos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_alter_configuracionbeneficiocategoria_limite_mensual_pyg_and_more'),
        ('cotizaciones', '0007_cargar_configuracion_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoAcreditacion',
            fields=[
                ('id_destino', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CUENTA_BANCARIA', 'Cuenta bancaria'), ('BILLETERA_ELECTRONICA', 'Billetera electrónica')], max_length=25, verbose_name='Tipo')),
                ('alias', models.CharField(blank=True, help_text='Nombre con el que querés identificar este destino.', max_length=60, verbose_name='Alias')),
                ('titular', models.CharField(max_length=150, verbose_name='Titular')),
                ('documento_titular', models.CharField(max_length=20, validators=[destinos.validators.validar_documento_titular], verbose_name='Documento del titular')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('CAJA_AHORRO', 'Caja de ahorro'), ('CUENTA_CORRIENTE', 'Cuenta corriente')], max_length=20, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, validators=[destinos.validators.validar_numero_cuenta], verbose_name='Número de cuenta')),
                ('proveedor_billetera', models.CharField(blank=True, max_length=100, verbose_name='Proveedor de la billetera')),
                ('numero_billetera', models.CharField(blank=True, max_length=20, validators=[pagos.validators.validar_numero_billetera], verbose_name='Celular asociado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos_acreditacion', to='clientes.cliente', verbose_name='Cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos_acreditacion', to='cotizaciones.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Destino de acreditación',
                'verbose_name_plural': 'Destinos de acreditación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaDestinoAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('DESACTIVACION', 'Desactivación'), ('ACTIVACION', 'Activación'), ('ELIMINACION', 'Eliminación')], max_length=20, verbose_name='Acción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_destinos', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='destinos.destinoacreditacion', verbose_name='Destino de acreditación')),
            ],
            options={
                'verbose_name': 'Auditoría de destino de acreditación',
                'verbose_name_plural': 'Auditorías de destinos de acreditación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='destinoacreditacion',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'CUENTA_BANCARIA')), fields=('cliente', 'moneda', 'numero_cuenta'), name='destino_cuenta_unica_por_cliente_moneda'),
        ),
    ]
