# Generated by Django 6.1 on 2026-09-25 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_metodopago_numero_billetera_and_more'),
        ('transacciones', '0002_transaccion_destino_acreditacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='pagos.metodopago', verbose_name='Metodo de pago'),
        ),
    ]
