# Generated by Django 6.1 on 2026-08-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
