# Generated by Django 6.1 on 2026-08-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('FISICA', 'Persona física'), ('JURIDICA', 'Persona jurídica')], default='FISICA', max_length=8),
            preserve_default=False,
        ),
    ]
