# Generated by Django 6.1 on 2026-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBeneficioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], max_length=11, unique=True)),
                ('porcentaje_beneficio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('limite_mensual_pyg', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
    ]
