# Generated by Django 6.1 on 2026-09-07 19:28

from django.db import migrations


def cargar_configuracion_beneficios(apps, schema_editor):
    ConfiguracionBeneficioCategoria = apps.get_model(
        "clientes",
        "ConfiguracionBeneficioCategoria",
    )

    categorias = [
        "MINORISTA",
        "CORPORATIVO",
        "VIP",
    ]

    for categoria in categorias:
        ConfiguracionBeneficioCategoria.objects.get_or_create(
            categoria=categoria,
            defaults={
                "porcentaje_beneficio": 0,
                "limite_mensual_pyg": 0,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_configuracionbeneficiocategoria"),
    ]

    operations = [
        migrations.RunPython(
            cargar_configuracion_beneficios,
            migrations.RunPython.noop,
        ),
    ]