# Generated by Django 6.1 on 2026-09-07 19:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cargar_configuracion_beneficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionbeneficiocategoria',
            name='limite_mensual_pyg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='configuracionbeneficiocategoria',
            name='porcentaje_beneficio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('30.00'))]),
        ),
    ]
