# Generated by Django 6.1 on 2026-09-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_configuracionbeneficiocategoria_limite_mensual_pyg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vip_vigente_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='VIP vigente hasta'),
        ),
    ]
