# Generated by Django 6.1 on 2026-09-28 21:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_vip_vigente_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_mensual_pyg', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Umbral mensual para VIP en PYG')),
                ('duracion_meses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración del VIP temporal en meses')),
            ],
        ),
    ]
