# Generated by Django 6.1 on 2026-09-28 22:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_configuracionvip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionvip',
            options={'verbose_name': 'Configuración VIP temporal', 'verbose_name_plural': 'Configuración VIP temporal'},
        ),
        migrations.AddField(
            model_name='configuracionvip',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='configuracionvip',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_vip_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='configuracionvip',
            name='duracion_meses',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración del VIP temporal en meses'),
        ),
        migrations.AlterField(
            model_name='configuracionvip',
            name='umbral_mensual_pyg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Umbral mensual para VIP en PYG'),
        ),
    ]
