# Generated by Django 6.1 on 2026-09-01 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('simbolo', models.CharField(max_length=8)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id_tasa', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_compra', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_venta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_vigencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_destino', to='cotizaciones.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_origen', to='cotizaciones.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['moneda_origen__codigo', 'moneda_destino__codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('moneda_origen', models.F('moneda_destino')), _negated=True), name='cotizaciones_tasa_monedas_distintas'), models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('moneda_origen', 'moneda_destino'), name='cotizaciones_tasa_vigente_unica_por_par')],
            },
        ),
    ]
