# Generated by Django 6.1 on 2026-09-08 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cargar_monedas_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.CreateModel(
            name='AuditoriaTasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Precio de compra anterior')),
                ('precio_venta_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Precio de venta anterior')),
                ('precio_compra_nuevo', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Precio de compra nuevo')),
                ('precio_venta_nuevo', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Precio de venta nuevo')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_tasas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('tasa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_como_anterior', to='cotizaciones.tasacambio', verbose_name='Tasa anterior')),
                ('tasa_nueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='cotizaciones.tasacambio', verbose_name='Tasa nueva')),
            ],
            options={
                'verbose_name': 'Auditoría de tasa de cambio',
                'verbose_name_plural': 'Auditorías de tasas de cambio',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
