# Generated by Django 6.1 on 2026-09-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auditoriamoneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriamoneda',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('DESHABILITACION', 'Deshabilitación'), ('HABILITACION', 'Habilitación')], max_length=20, verbose_name='Acción'),
        ),
    ]
