# Generated by Django 6.1 on 2026-09-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_tasacambio_modificado_por_auditoriatasacambio'),
        ('cotizaciones', '0004_alter_auditoriamoneda_accion'),
    ]

    operations = [
    ]
